name: ANgular CI

on: [push]

jobs:
  codacy-coverage-reporter:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Install dependencies
      run: npm install
    - name: Lint
      run: npm run lint
    - name: Test
      run: npm test -- --configuration=ci
    - name: Run codacy-coverage-reporter
      uses: codacy/codacy-coverage-reporter-action@master
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: ../coverage/clover.xml
    - name: Build
      run: npm run build -- --prod